Controllers/UserLoginController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using ktr_msc_ls1_BCM.Models;

namespace ktr_msc_ls1_BCM.Controllers
{
    public class UserLoginController : Controller
    {

        private readonly Entities db = new Entities();
        // GET: UserLogin
        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }



        [HttpPost]
        public ActionResult Login(Models.Profile model)
        {

            using (var context = new Entities())
            {

                //string pass = Encrypt(model.Password);
                bool isValid = context.Profiles.Any(x => x.Username == model.Username && x.Password == model.Password);
                if (isValid)
                {
                    FormsAuthentication.SetAuthCookie(model.Username, true);
                    var useriD = from us in db.Profiles
                                 where us.Username == model.Username
                                 select us.Id;

                    Session["username"] = model.Username;
                    Session["Id"] =useriD.First();

                    return RedirectToAction("Index", "Profiles");
                    //return RedirectToAction(Request.UrlReferrer.ToString());

                }

                ModelState.AddModelError("", "Invalid username or password");

                return View();
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,Firstname,Lastname,Status,Username,Password")] Profile profile)
        {
            if (ModelState.IsValid)
            {
                profile.Status = "Active";
                db.Profiles.Add(profile);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(profile);
        }

        public string Encrypt(string clearText)
        {
            string EncryptionKey = "MAKV2SPBNI99212";
            byte[] clearBytes = Encoding.Unicode.GetBytes(clearText);
            using (Aes encryptor = Aes.Create())
            {
                Rfc2898DeriveBytes pdb = new Rfc2898DeriveBytes(EncryptionKey, new byte[] { 0x49, 0x76, 0x61, 0x6e, 0x20, 0x4d, 0x65, 0x64, 0x76, 0x65, 0x64, 0x65, 0x76 });
                encryptor.Key = pdb.GetBytes(32);
                encryptor.IV = pdb.GetBytes(16);
                using (MemoryStream ms = new MemoryStream())
                {
                    using (CryptoStream cs = new CryptoStream(ms, encryptor.CreateEncryptor(), CryptoStreamMode.Write))
                    {
                        cs.Write(clearBytes, 0, clearBytes.Length);
                        cs.Close();
                    }
                    clearText = Convert.ToBase64String(ms.ToArray());
                }
            }
            Decrypt(clearText);
            return clearText;
        }
        public string Decrypt(string cipherText)
        {
            string EncryptionKey = "MAKV2SPBNI99212";
            byte[] cipherBytes = Convert.FromBase64String(cipherText);
            using (Aes encryptor = Aes.Create())
            {
                Rfc2898DeriveBytes pdb = new Rfc2898DeriveBytes(EncryptionKey, new byte[] { 0x49, 0x76, 0x61, 0x6e, 0x20, 0x4d, 0x65, 0x64, 0x76, 0x65, 0x64, 0x65, 0x76 });
                encryptor.Key = pdb.GetBytes(32);
                encryptor.IV = pdb.GetBytes(16);
                using (MemoryStream ms = new MemoryStream())
                {
                    using (CryptoStream cs = new CryptoStream(ms, encryptor.CreateDecryptor(), CryptoStreamMode.Write))
                    {
                        cs.Write(cipherBytes, 0, cipherBytes.Length);
                        cs.Close();
                    }
                    cipherText = Encoding.Unicode.GetString(ms.ToArray());
                }
            }
            return cipherText;
        }

    }
}

Views/UserLogin/Create.cshtml
@model ktr_msc_ls1_BCM.Models.Profile

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Profile</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
                @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Company, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Company, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phonenumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phonenumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phonenumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/UserLogin/Login.cshtml
@model ktr_msc_ls1_BCM.Models.Profile
    
@{ 
    ViewBag.Title = "View";
}

<h2>View</h2>

<!DOCTYPE html>
<html lang="en">
<head>
    <title>AVSI</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" type="image/png" href="~/images/icons/avatar-01.ico" />

 

    <link rel="stylesheet" type="text/css" href="~/Content/util.css">
    <link rel="stylesheet" type="text/css" href="~/Content/main.css">
    <!--===============================================================================================-->
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="limiter" id="logindiv">
            <div class="container-login100" @*style="background-image: url('https://cdn.shortpixel.ai/client/q_glossy,ret_img/../images/img-01.jpg');"*@>
                <div class="wrap-login100 p-t-50 p-b-0">
                    <form class="login100-form validate-form">
                        <div class="login100-form-avatar">
                            <img src="~/images/avatar-01.jpg" alt="AVATAR">
                        </div>
                        <span class="login100-form-title p-t-20 p-b-45">
                          EPITECH BUSINESS CARD MANAGER
                        </span>


                        <div class="wrap-input100 validate-input m-b-10" data-validate="Username is required">

                            <div class="wrap-input100 validate-input m-b-10">
                                <span class="focus-input100"></span>
                                <span class="symbol-input100">
                                    <i class="fa fa-user"></i>
                                </span>
                                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "input100", placeholder = "Username" } })
                                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="wrap-input100 validate-input m-b-10" data-validate="Password is required">
                            @*<input class="input100" type="password" name="password" id="password" placeholder="Password">*@
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <i class="fa fa-lock"></i>
                            </span>
                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "input100", placeholder = "Password" } })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>

                        <div class="container-login100-form-btn p-t-10">
                            <input type="submit" value="Login" class="login100-form-btn" id="loginbutton">
                            <a id="btn-add" class="btn-google" onclick="location.href= '@Url.Action("Register", "UserLogin")'"><i class="fa fa-link"></i> Register</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div style="    margin: auto;  text-align:center;   position: fixed;  top: 50%;  left: 50%;  /* bring your own prefixes */  transform: translate(-50%, -50%);">
            <div id="divLoader" style="display:none; " class="lds-hourglass"></div>
        </div>

    }
    <!--===============================================================================================-->
    <script src="~/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    @*<script src="~/vendor/bootstrap/js/popper.js"></script>*@
    @*<script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>*@
    <!--===============================================================================================-->
    <script src="~/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    @*<script src="~/Scripts/main.js"></script>*@
</body>


</html>